[workspace]
exclude = ["test_wasm_bins/demo_cli","test_wasm_bins/promise_wasm_bin"]
members = [
	"adapters/chain",
	"adapters/http",
	"adapters/p2p",
	"adapters/runtime",
	"adapters/storage",
	"cli",
	"config",
	"contracts",
	"logger",
	"node",
	"runtime/core",
	"runtime/macros",
]

[profile.dev]
codegen-units = 512
debug = 2
incremental = true
opt-level = 0

[profile.release]
codegen-units = 1
incremental = false
lto = "thin"
opt-level = 3
panic = "abort"
strip = true

[profile.release-docker]
inherits = "release"
opt-level = "z"
