[workspace]
members = [
	"cli",
	"contracts",
	"node",
	"runtime/core",
	# Commmented since it breaks test all locally and in CI.
	# "runtime/core/test_res/promise_wasm_bin",
	"runtime/macros",
	"adapters"
]

[profile.dev]
codegen-units = 512
debug = 2
incremental = true
opt-level = 0

[profile.release]
codegen-units = 1
incremental = false
lto = "thin"
opt-level = 3
panic = "abort"
split-debuginfo = '...'
strip = true

[profile.release-docker]
inherits = "release"
opt-level = "z"
