seda_server_address = '127.0.0.1'
seda_server_port = 12345
[chains.another]
chain_rpc_url = 'https://rpc.testnet.near.org'

[chains.near]
chain_rpc_url = 'https://rpc.testnet.near.org'

[node]
contract_account_id = 'fill this in'
public_key = 'fill this in'
secret_key = 'fill this in'
signer_account_id = 'fill this in'

[logging]
log_file_path = 'C:\Users\galu\Documents\work\Flux\seda-rust'
