[package]
name = "seda-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.15", default-features = true, features = ["derive"] }
tokio = { version = "1.16", features = ["full"] }
anyhow = "1"
serde_json = { version = "1" }
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee.git", branch = "master", features = ["full"] }

dotenv = "0.15.0"

seda-node = { path = "../node" }





near-jsonrpc-client = { version="0.4.0", default-features = false, features = ["auth","rustls-tls"] }
near-jsonrpc-primitives = "0.15.0"
near-primitives = "0.15.0"
# tokio =  { version = "1.21.2", default-features = false, features = ["io-std", "macros", "net", "rt-multi-thread", "time"] }
# serde_json = "1.0.87"
near-crypto = "0.15.0"
env_logger = "0.9.1"
serde = "1.0.145"
# dotenv = "0.15.0"




[[bin]]
name = "seda"
path = "src/main.rs"