[package]
name = "seda-http-adapters"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.58"
reqwest = "0.11.12"
seda-runtime-adapters = { path = "../runtime" }
thiserror = "1.0.37"
