[package]
name = "seda-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = { version = "0.13.0" }
anyhow = "1"
console-subscriber = "0.1.8"
dotenv = "0.15.0"
futures = "0.3"
hyper = "0.14.20"
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee.git", branch = "master", features = ["full"] }
jsonrpsee-core = "0.15.1"
log = "0.4"
seda-contracts-adapter = {path = "../adapter"}
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
serde_json = { version = "1" }
tokio = { version = "1.21.2", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
toml = { version = "0.5.9", default-features = false }
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.3.4", features = ["full"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }