[package]
name = "seda-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = { version = "0.13.0" }
async-trait = "0.1.58"
futures = "0.3.25"
jsonrpsee-core = "0.15.1"
jsonrpsee-ws-server = "0.15.1"
parking_lot = "0.12"
reqwest = "0.11.12"
seda-adapters = { path = "../adapters" }
seda-config = { path = "../config" }
seda-runtime = { path = "../runtime/core" }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
tokio = { version = "1.21.2", features = ["full"] }

rusqlite = "0.28.0"
tokio-rusqlite = "0.3.0"
