[package]
name = "seda-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = { version = "0.13.0" }
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
tokio = { version = "1.21.2" }
toml = { version = "0.5.9", default-features = false }
