[package]
name = "seda-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# anyhow = "1"
# futures = "0.3"
actix = { version = "0.13.0" }
anyhow = "1"
console-subscriber = "0.1.8"
dotenv = "0.15.0"
env_logger = "0.9.1"
futures = "0.3"
hyper = "0.14.20"
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee.git", branch = "master", features = ["full"] }
jsonrpsee-core = "0.15.1"
jsonrpsee-ws-server = "0.15.1"
log = "0.4"
near-crypto = "0.15.0"
near-jsonrpc-client = { version="0.4.0", default-features = false, features = ["auth","rustls-tls"] }
near-jsonrpc-primitives = "0.15.0"
near-primitives = "0.15.0"
seda-contracts-adapter = {path = "../adapter"}
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
serde_json = "1.0.87"
tokio = { version = "1.21.2", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
toml = { version = "0.5.9", default-features = false }
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.3.4", features = ["full"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }