[package]
name = "seda-contracts"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
