[package]
name = "seda-runtime"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
async-trait = { workspace = true }
bn254 = { workspace = true }
futures = { workspace = true, features = ["executor"] }
hex = { workspace = true }
parking_lot = { workspace = true }
reqwest = { workspace = true }
seda-chains = { workspace = true }
seda-config = { workspace = true }
seda-runtime-sdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
wasmer = { workspace = true }
wasmer-cache = { workspace = true }
wasmer-wasix = { workspace = true }


[dev-dependencies]
lazy_static = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
seda-crypto = { workspace = true }
