[package]
name = "seda-runtime"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
actix = { workspace = true }
async-trait = { workspace = true }
parking_lot = { workspace = true }
seda-runtime-adapters = { workspace = true }
seda-runtime-sdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
wasmer = { workspace = true }
wasmer-wasi = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true }
seda-runtime-adapters = { workspace = true, features = ["test_host"] }
# rusqlite = { version = "0.28.0", features = ["bundled"] }
tokio-rusqlite = "0.3.0"
futures = "0.3.25"
seda-chain-adapters = {workspace = true}

lazy_static = "1.4.0"
borsh = "0.9.3"
dotenv = "0.15.0"
