[package]
name = "seda-runtime-sdk"
version = "0.1.0"
edition = "2021"

[features]
default = []
wasm = []

[dependencies]
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0"
parse-display = "0.6.0"
